#!/usr/bin/make -f
# Makefile for zam-plugins #
# ------------------------ #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = ZamEQ2

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	ZamEQ2Plugin.cpp.o

OBJS_UI  = \
	ZamEQ2Artwork.cpp.o \
	ZamEQ2UI.cpp.o

# --------------------------------------------------------------
# No custom UI for now

#TARGET_NOUI = true

# --------------------------------------------------------------
# Do some magic

include ../Makefile.mk

# --------------------------------------------------------------
