#!/usr/bin/make -f
# Makefile for zam-plugins #
# ------------------------ #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = ZaMultiComp

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	ZaMultiCompPlugin.cpp.o

OBJS_UI  = \
	ZaMultiCompArtwork.cpp.o \
	ZaMultiCompUI.cpp.o

# --------------------------------------------------------------
# No custom UI for now

TARGET_NOUI = true

# --------------------------------------------------------------
# Do some magic

include ../Makefile.mk

# --------------------------------------------------------------
