#!/usr/bin/make -f
# Makefile for zam-plugins #
# ------------------------ #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = ZamAutoSat

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	ZamAutoSatPlugin.cpp.o

OBJS_UI = \
	ZamAutoSatArtwork.cpp.o \
	ZamAutoSatUI.cpp.o

# --------------------------------------------------------------
# No custom UI for now

#TARGET_NOUI = true

# --------------------------------------------------------------
# Do some magic

include ../Makefile.mk

# --------------------------------------------------------------
